fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      ref: 'master'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
  symlinks:
    ibm_installation_manager: "#{source_dir}"
