---
.travis.yml:
  docker_sets: []
  docker_defaults:
    bundler_args: ""
  secure: ""
  branches:
    - release

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw

appveyor.yml:
  delete: true

.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml

Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint

.gitlab-ci.yml:
  unmanaged: true
